# Generated by Django 4.0.1 on 2022-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_image',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.png', upload_to='images')),
            ],
        ),
    ]
